name: Long Running Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run long running task
        run: |
          # Add your long running task here
          sleep 120

      - if: false
        name: fail on purpose
        run: exit 1

      - name: Complete workflow
        run: echo "Workflow completed"
