name: Release
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for other workflow to complete
        if: '!startsWith(github.event.pull_request.title, "feat: Release")'
        run: |
          while :; do
            result=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs | \
              jq -r '.workflow_runs | map(select(.name == "Long Running Workflow")) | sort_by(.created_at) | reverse | .[0]')
            status=$(echo "$result" | jq -r '.status')
            conclusion=$(echo "$result" | jq -r '.conclusion')
            if [[ "$status" == "completed" ]]; then
              if [[ "$conclusion" == "success" ]]; then
                echo "Long Running Workflow completed successfully"
                break
              else
                echo "Long Running Workflow failed"
                exit 1
              fi
            elif [[ "$status" == "in_progress" ]]; then
              echo "Long Running Workflow is still running"
              sleep 60
            else
              echo "Unexpected status: $status"
              exit 1
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Release
        run: |
          # Add your long running task here
          sleep 10
          echo "Release"

      - name: Complete workflow
        run: echo "Release completed"
