name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default:
    name: Default test
    runs-on: ubuntu-latest
    if: |
      (!startsWith(github.ref, 'refs/heads/release-') && 
      !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'release-'))) ||
      !(github.event_name == 'push' && startsWith(github.head_ref, 'release-'))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Debug github context
        run: echo "${{ toJson(github) }}"