name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-changes:
    name: Verify changes
    runs-on: ubuntu-latest
    outputs:
      run_backend_tests: ${{ steps.set-outputs.outputs.backend_tests }}
      run_ui_tests: ${{ steps.set-outputs.outputs.ui_tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            backend:
              - 'backend/**'
              - 'shared/**'
            ui:
              - 'ui/**'
              - 'shared/**'
      - name: Set outputs
        id: set-outputs
        shell: bash
        run: |
          echo "backend_tests=${{ steps.changed-files.outputs.backend_any_changed }}" >> "$GITHUB_OUTPUT"
          echo "ui_tests=${{ steps.changed-files.outputs.ui_any_changed }}" >> "$GITHUB_OUTPUT"
  
  backend-tests:
    if: ${{ needs.check-changes.outputs.run_backend_tests == 'true' }}
    name: Backend tests
    needs: check-changes
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run backend tests
      run: |
        echo "Running backend tests"
        sleep 10

  ui-tests:
    if: ${{ needs.check-changes.outputs.run_ui_tests == 'true' }}
    name: UI tests
    needs: check-changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ui tests
        run: |
          echo "Running UI tests"
          sleep 10

