name: Test

on:
  push:
    branches:
      - main
      - '!release-*'
  pull_request:
    branches:
      - main

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref: ${{ github.ref }}"

  validate:
    name: Validate branch
    runs-on: ubuntu-latest
    if: | 
      !startsWith(github.head_ref, 'release-')

    steps:
      - name: debug
        run: |
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref: ${{ github.ref }}"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


  default:
    name: Default test
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug github context
        run: echo "${{ toJson(github) }}"
